- all_wells: [ACRUS1, BIGL22, MOOM115, POND1, POND14, POND16, PSYC3, PSYC7, TIRRA80, TIRRA88, TIRRA91, TIRRA93, TIRRW1, TOOL29, WELTN1, WIPPOS1, YAN1L, YAN2L, YAN2U, YAN4U, YAN8L, WKT3]
  test_wells: [POND1]
  features: [ROC_VOLTAGE,FLOW]
  num_days: 1
  normalise_mode: all
  base_lr: 0.005
  early_stopping_patience: 15 
  reduce_lr_patience: 7
  batch_size: 32
  optimiser: adam
  num_epochs: 100
  metrics: ['mae','mse']
  use_pretrain: False 
  pretrain_model: 
  save_model: True
  save_name: regressor_POND1
