- all_wells: ['BIGL20', 'BIGL22', 'MOOM115', 'MOOM157', 'WKT3']
  test_wells: [WKT3]
  features: [ROC_VOLTAGE, Mask_ROC_VOLTAGE, 'temperature_2m', 'cloudcover','cloudcover_low', 'cloudcover_mid', 'cloudcover_high', 'shortwave_radiation', 'direct_radiation', 'diffuse_radiation', 'direct_normal_irradiance']
  num_days: 1
  last_day: 2022-06-30
  normalise_mode: all
  base_lr: 0.0005
  early_stopping_patience: 15 
  reduce_lr_patience: 7
  label_mapping: { 0 : 0, 9 : 1}
  drop_labels: [1,2,3,4,5,6,7,8]
  batch_size: 32
  optimiser: adam
  num_epochs: 100
  metrics: [acc,iou]
  use_pretrain: False 
  pretrain_model: 
  save_model: True
  save_name: weather_model
