- all_wells:
  - ACRUS1
  - BIGL22
  - MOOM115
  - POND1
  - POND11
  - POND14
  - POND16
  - PSYC3
  - PSYC7
  - TIRRA80
  - TIRRA88
  - TIRRA91
  - TIRRA93
  - TIRRW1
  - TOOL29
  - WELTN1
  - WIPPOS1
  - WKT3
  - YAN1L
  - YAN2L
  - YAN2U
  - YAN4U
  - YAN8L
  processed_wells:
  - ACRUS1
  - MOOM115
  - POND1
  - POND11
  - POND14
  - POND16
  - PSYC3
  - PSYC7
  - TIRRA80
  - TIRRA88
  - TIRRA91
  - TIRRA93
  - TIRRW1
  - TOOL29
  - WELTN1
  - WIPPOS1
  - YAN1L
  - YAN2L
  - YAN4U
  - YAN8L
  - BIGL22
  - WKT3
  - YAN2U
